language: node_js
node_js:
  - 10
install:
  - cd ../ && git clone -b fix-1432 https://github.com/raysonkoh/markbind.git && cd markbind/packages/cli && npm link && cd ../../ && npm run setup && cd ../test_markbind
script: markbind build
deploy:
  provider: script
  script: markbind deploy --ci
  skip_cleanup: true
  on:
    branch: master