environment:
  nodejs_version: '10'

branches:
  only:
    - master

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i -g git://github.com/raysonkoh/test-dep-markbind.git
  - markbind build
  - markbind deploy --ci

test: off

build: off