jobs:
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: "10"
          install-yarn: true
      - run: node --version
version: 2.1
orbs:
  node: circleci/node@4.1.0
workflows:
  Deploy:
    jobs:
      - deploy
