jobs:
  Deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: 10
          install-yarn: true
      - run: node --version
orbs:
  node: circleci/node@x.y
