name: Test Markbind
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    name: test
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: cd ../ && git clone -b fix-1432-gh-action-2 https://github.com/raysonkoh/markbind.git
      - run: cd ../markbind/packages/cli && npm link
      - run: cd ../markbind && npm run setup
      - run: markbind build
      - run: markbind deploy --ci