name: Test Markbind
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: cd ../ && git clone -b fix-1432-gh-action https://github.com/raysonkoh/markbind.git
      - run: cd markbind/packages/cli && npm run link
      - run: cd ../../ && npm run setup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      