jobs:
  build:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: npm install markbind-cli
      - run: npm run build