name: Deploy PR Preview

# Runs after PR is received and build by markbind-cli
# Has access to repo secrets
on:
  workflow_run:
    workflows: ["Receive Markbind PR"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: receivePR.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: markbind-deployment
          path: .
      - name: Display structure of downloaded files
        run: ls -R
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 10
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Install surge and deploy PR to surge
        run: |
          npm i -g surge
          surge --project ./_site --domain https://pr-${{ github.event.number }}-${{ env.GITHUB_REPOSITORY_SLUG_URL }}.surge.sh/ 
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
