name: Deploy PR Preview

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install surge and fire deployment
        uses: actions/setup-node@v2
        with:
          node-version: 10
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Deploy PR to Surge
        run: |
          echo "${{ env.SLUG_URL }}"
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
